### ISSUE TITLE
Infinite loop in nested routes

### ISSUE THREAD

**Issue by arieroos** [EmilTholin/svelte-routing#242]
Hi

Please see my example project for reference: https://github.com/arieroos/minimal-breaking-example
This project works with version 1.6.0, but it breaks in 1.8.5

I'm a little unsure how to describe the exact issue. But as you'll see in the example, I have components with nested routes. When I open such a component the router goes into an infinite loop trying to load my component over and over.

I have the same set-up (just a little more complex) in a production project. That project has now been restricted to use version 1.6 of svelte-routing. If I try to use version 1.8, my project breaks. It would be great if this issue can be resolved, so that I can stay up to date with package versions.

Thanks

**Comment by krishnaTORQUE** [comment]
Hi @EmilTholin 
Any idea about it?
I am still unable to find the issue.

**Comment by spassvogel** [comment]
Yup definitely a problem

**Comment by krishnaTORQUE** [comment]
I resolved the issue but unable to push the code due to github outage.
Once github outage is resolve I will push the code & publish on npm.
Thanks

https://www.githubstatus.com/

**Comment by krishnaTORQUE** [comment]
Issue has been fixed in v1.8.6

**Comment by kryptus36** [comment]
I'm still seeing this behavior with 1.8.7 and all other deps updated.

It seems any time I try to nest routes even in the simplest case this happens.

```
<script>
  import {Link, Route, Router} from "svelte-routing";
</script>

<main>
  <div>
    <Router>
      <nav>
        <Link to="/nested">Nested</Link>
      </nav>

      <Route>ok</Route>
      <Route path="/nested">
        <Router basepath="/nested">
          <Route>Hi from nested. Accessing this route will freeze your browser</Route>
        </Router>
      </Route>
    </Router>
  </div>
</main>
```

![image](https://github.com/EmilTholin/svelte-routing/assets/8608478/ce4328b9-0e1d-4693-8104-c286a4cdabcc)


"devDependencies": {
    "@sveltejs/vite-plugin-svelte": "^2.2.0",
    "svelte": "^3.59.1",
    "svelte-routing": "^1.8.7",
    "vite": "^4.3.5"
  }

**Comment by krishnaTORQUE** [comment]
> I'm still seeing this behavior with 1.8.7 and all other deps updated.
> 
> It seems any time I try to nest routes even in the simplest case this happens.
> 
> ```
> <script>
>   import {Link, Route, Router} from "svelte-routing";
> </script>
> 
> <main>
>   <div>
>     <Router>
>       <nav>
>         <Link to="/nested">Nested</Link>
>       </nav>
> 
>       <Route>ok</Route>
>       <Route path="/nested/*">
>         <Router basepath="/nested">
>           <Route>Hi from nested. Accessing this route will freeze your browser</Route>
>         </Router>
>       </Route>
>     </Router>
>   </div>
> </main>
> ```
> 
> ![image](https://user-images.githubusercontent.com/8608478/237200158-ce4328b9-0e1d-4693-8104-c286a4cdabcc.png)
> 
> "devDependencies": { "@sveltejs/vite-plugin-svelte": "^2.2.0", "svelte": "^3.59.1", "svelte-routing": "^1.8.7", "vite": "^4.3.5" }

I ran this exact code & did not get any issue.
Tested on Firefox & Chrome.

**Comment by kryptus36** [comment]
That's really weird. I'm running node 18.16. I don't know what other difference there could be.

**Comment by krishnaTORQUE** [comment]
I am running the same version.
I will let this issue open for sometime.

**Comment by kryptus36** [comment]
I spent most of the day today trying to figure this out. It works for me in 1.6 but not 1.8. @arieroos  and @spassvogel please check back and let us know how it works for you. I am unfortunately out of ideas. I'll just use 1.6 for now.

**Comment by krishnaTORQUE** [comment]
> I spent most of the day today trying to figure this out. It works for me in 1.6 but not 1.8. @arieroos and @spassvogel please check back and let us know how it works for you. I am unfortunately out of ideas. I'll just use 1.6 for now.

If possible please make a repo with minimum reproduce, so I can check again.
The above code is working fine.
Thanks

**Comment by spassvogel** [comment]
With `1.8.7` I still have an infinite loop in Chrome and FF

**Comment by arieroos** [comment]
Yes. I can confirm it's still broken. I updated the minimal breaking example, and it is still going into an infinite loop. Tested with FF

**Comment by arieroos** [comment]
I can conform that is working in my minimal example, and in my production project.

Thank you @krishnaTORQUE

**Comment by krishnaTORQUE** [comment]
> I can conform that is working in my minimal example, and in my production project.
> 
> Thank you @krishnaTORQUE

Great
@arieroos welcome

**Comment by kryptus36** [comment]
Works for me as well. Nicely done! I'm trying to get caught up n the code base so I can be a bit more helpful. But thank you @krishnaTORQUE !
